# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_github_packages:
  - r-lib/covr

after_success:
  - travis_wait 180 Rscript -e 'covr::codecov()'
